3box/ceramic-tests

Cargo.lock, hermetic/src/cli/tester.rs
Using the TTL on networks that should be cleaned up means we do not have to be as careful to clean up the network after a driver failure. Instead we can leave it around for investigation and be confident it will eventually be cleaned up by the operator.
=> feat: set network TTL when clean_up is set

.github/workflows/run-durable.yml, .github/workflows/schedule-durable.yml, Makefile, ci-scripts/schedule_durable_tests.sh
This PR splits the durable tests workflow into two phases:
- The first phase is building and publishing the test image, then scheduling a workflow job with the CD manager via [this](https://github.com/3box/pipeline-tools/pull/53) PR.
- The second phase is running the tests once the CD manager initiates the workflow.
=> feat: tracked durable tests

durable/durable-driver.sh, suite/Dockerfile, suite/docker-compose.yml
All tests were defaulting to the "dev" settings and hitting the Dev nodes instead of the right nodes in each respective env. This change should fix that.
=> fix: inject correct .env path for durable tests

suite/src/__tests__/fast/update.test.ts, suite/src/__tests__/slow/ceramic-ceramic-integration.test.ts
"All" tests are [passing](https://github.com/3box/ceramic-tests/actions/runs/7633510819/job/20795877501) with the one suite skipped.
The tests in the suite [fail](https://github.com/3box/ceramic-tests/actions/runs/7633493677/job/20795826460) otherwise.
=> chore: skip failing tests

.github/workflows/create-release.yml, Cargo.lock, Cargo.toml, Dockerfile.hermetic-driver, Makefile, ci-scripts/publish_hermetic_driver.sh, hermetic/Cargo.toml
Statically compile openssl for the hermetic driver release.
Fixed the release steps.
=> fix: release workflow

suite/src/__tests__/fast/get-events.test.ts, suite/src/utils/rustCeramicHelpers.ts
E2E tests for fetching event data from event_id (string). 
Goal is to test the getEvent endpoint end-to-end.
Scenarios tested : 
Positive scenario: StatusCode 200 : Publish and event, and then fetch event data for the same event
Negative scenario: StatusCode 404 (Event Not found) : Fetch eventData for an eventId that does not exist
PR testing : 
Ran the setup locally :
=> feat: ws1 1455 e2e test for get events

simulations/basic-simulation.yaml
Target 300 rps (should be slightly above in practice, but we want to make sure we write at least that many). Error if any run is less than 200 rps. When we reduce the variations in the runs due to hardware differences, we can increase this value, but for now it's below the lowest value we've seen in 24 hours (238 rps).
=> chore: update nightly simulation rate and target

port-forward.sh
The port-forward script will now read the ceramic-admin secret and export the env var.
=> feat: export the COMPOSEDB_ADMIN_SEEDS env via port-forward

.github/workflows/hermetic.yml, networks/basic-rust.yaml
The github action for checking performance are failing on the non auto-pilot cluster.
This PR updates the action's network to use the same resources as the nightly-performance runs.
=> fix: give perf tests more resources

ci-scripts/schedule_durable_tests.sh
Using the new `labels` field enabled via [this](https://github.com/3box/pipeline-tools/pull/58) PR.
=> fix: pass test job label to designate notification channel

suite/src/__tests__/fast/model-correctness.test.ts
Skipping e2e tests that are failing on durable envs
=> fix: skip failing tests

suite/src/__tests__/fast/sync-events.test.ts
WS2-3008
We have a GET events by filter route that isn't officially supported and currently exists for testing and debugging (added in [this pr](https://github.com/ceramicnetwork/rust-ceramic/pull/286). Now we use it in tests so the official looking route can be deleted.
=> chore: use experimental get events route

suite/src/__tests__/fast/composedb-model-sync.test.ts
Changes to fix flakiness of composedb-model-sync test. 
Fix : Wait for the model to be present on the second node before indexing it, because recon takes some time to sync.
This would fix flaky test failures.
=> fix: add wait before indexing

suite/Dockerfile
Image is failing to build with
```
#11 [6/7] RUN pnpm install
#11 0.554  ERR_PNPM_BAD_PM_VERSION  This project is configured to use v^8.8.0 of pnpm. Your current pnpm is v9.0.1
#11 ERROR: process "/bin/sh -c pnpm install" did not complete successfully: exit code: 1
```
=> fix: for the use of pnmp v8

suite/src/__tests__/fast/get-events.test.ts, suite/src/__tests__/fast/sync-events.test.ts
Skip tests that store invalid/fake event data in ceramic one. Until we validate, the noise in durable environments is distracting, so it's better to turn them off while we sort out real vs phantom bugs.
We're also removing the event ID from the API, so these are going red while we stabilize. That's also distracting, so we can turn them back on when they are real, or can be replaced by the MID versions.
We do still have a sync test that verifies a document created on one node syncs to the other, we just don't have quite the same coverage of specific recon scenarios.
=> chore: disable tests that store invalid ceramic events in recon

simulations/basic-simulation.yaml
The api adds up to 10 ms of latency if there isn't enough traffic to flush early (3 requests). So 2 users were now hitting 8 ms requests instead of 1 ms, which caused 205/198 instead of the 275/250 we were getting before (with a required number of 200, even though were up from 91% to 96% of events synced). We add a few more users, which should still be throttled to the target rate of 300.
Compare the [failure](https://github.com/3box/ceramic-tests/actions/runs/8902327149/job/24448095212#step:6:127) to an older [success](https://github.com/3box/ceramic-tests/actions/runs/8840948790/job/24277257345#step:6:125) and notice the `POST create_new_event` Avg (ms) value difference. The API was changed recently in [this PR](https://github.com/ceramicnetwork/rust-ceramic/pull/324).
Kicked off [this …
=> chore: increase user count for simulation

.github/workflows/run-durable.yml, suite/env/.env.dev, suite/env/.env.prod, suite/env/.env.qa, suite/env/.env.tnet, suite/src/__tests__/fast/data-feed-api.test.ts
- Use Tailscale instead of kubectl port-forward for accessing durable nodes.
- Set static Tailscale endpoints for the tests.
- Skip datafeed api test as it's failing.
=> feat: tailscale for durable node access

Makefile, networks/basic-rust.yaml
We're tying up lots of node resources in GCP with idle tests.
This should clean them up after an hour.
=> fix: shorten basic-rust network ttl

README.md, suite/package.json, suite/pnpm-lock.yaml, suite/src/__tests__/fast/get-events.test.ts, suite/src/__tests__/fast/sync-events.test.ts, suite/src/utils/rustCeramicHelpers.ts
This change is made in order to stay compatible with the [new ceramic one api](https://github.com/ceramicnetwork/rust-ceramic/pull/327), where we accept CID instead of EventID. The recon input and output are now different, so I created a second interface to help get the create/assert right.
I made some adjustments to events and we now build a valid ceramic deterministic event so that recon can parse and sync it. I used the unique field of a deterministic event to avoid signing and make sure they were different so that recon would sync each of them.
=> chore: c1 get event accepts CID now

suite/src/__tests__/fast/model-correctness.test.ts, suite/src/utils/common.ts, suite/src/utils/composeDbHelpers.ts
This test was failing intermittently with an error of 'Error message : 'Internal Server Error': ***"error":"block was not found locally (offline)'
This error was being thrown from line : https://github.com/ceramicnetwork/js-ceramic/blob/51369364bfe9f6b63eac2af500f7427d476d7430/packages/core/src/state-management/repository.ts#L245. 
Thus if we wait for the model to be indexed and synced, this test would become more robust.
Discord thread link for investigations : https://discord.com/channels/484729862368526356/1215688378213867530/1238527178115780709
=> fix: add timeout to wait for model to index and load

suite/src/__tests__/fast/anchor.test.ts, suite/src/__tests__/fast/longevity.test.ts, suite/src/__tests__/fast/model-correctness.test.ts, suite/src/__tests__/fast/update.test.ts, suite/src/models/modelConstants.ts, suite/src/utils/ceramicHelpers.ts, suite/src/utils/composeDbHelpers.ts
The fact that the update test has been skipped for so long, means that the anchor and longevity tests have also effectively been skipped as well since they'll never find any documents in the database to test against.
This PR makes several changes:
- Adds updates to the explicit model-correctness.test.ts
- Re-enables update.test.ts after switching it to use MIDs instead of TileDocuments
- Updates anchor.test.ts and longevity.test.ts to work with streams in the database that are either TileDocuments OR ModelInstanceDocuments.
=> feat: Restore test coverage of updates

suite/src/__tests__/fast/get-events.test.ts, suite/src/utils/rustCeramicHelpers.ts
this test will fail for now, until https://linear.app/3boxlabs/issue/WS1-1633/disallow-unexpected-metadata-fields-in-events is implemented.
=> feat: Add test case for writing event with invalid metadata

suite/src/__tests__/fast/composedb-model-sync.test.ts, suite/src/__tests__/fast/model-correctness.test.ts, suite/src/__tests__/fast/update.test.ts, suite/src/__tests__/slow/ceramic-ceramic-integration.test.ts, suite/src/utils/ceramicHelpers.ts, suite/src/utils/composeDbHelpers.ts
No real functional change, doesn't change any of the timeouts, just switches strategy from waiting a fixed time and then expecting the data to have synced to polling to see if the data has been synced instead.  Wanted to isolate this change from any changes that actually increase the timeout, which will come next.
=> chore: Poll for data to sync instead of sleeping

suite/src/__tests__/fast/composedb-model-sync.test.ts, suite/src/__tests__/fast/model-correctness.test.ts, suite/src/__tests__/fast/update.test.ts
Hope is that this will get the QA durable tests passing long enough to hold us over until the RedTree lands and improves the sync time here.
=> fix: increase sync timeout

suite/src/__tests__/fast/sync-events.test.ts
10 retries, each with a 1 minute timeout, across 2 nodes, meant that each individual test within this file took 20 minutes to fail.  With 5 tests in the file, that means the test an hour and 40 minutes to fail if syncing isn't working.  This felt excessive.
With this change now there's just the 1 minute timeout per node per test, so 10 minutes total to fail if things aren't working.
=> chore: fail faster if syncing events is timing out

.github/workflows/run-performance.yaml
=> feat: use workflow for performance tests

port-forward.sh, suite/env/.env.dev, suite/env/.env.prod, suite/env/.env.qa, suite/env/.env.tnet, suite/src/__tests__/correctness/fast/sync-events.test.ts
Changes the default ports ceramic one uses for the RPC to 5101. See related changes in [rust-ceramic](https://github.com/ceramicnetwork/rust-ceramic/pull/411) and [keramik](https://github.com/3box/keramik/pull/194).
I also changed the tests to find the expected events only, as we were counting time events and anything else happening in our set which made the tests flaky.
=> chore: change default ceramic-one ports

.github/workflows/run-performance.yaml, notifications/notification-template.json, performance/README.md, performance/ceramic-anchoring-benchmark/network.yaml, performance/ceramic-anchoring-benchmark/simulation.yaml, performance/ceramic-new-streams/network.yaml, performance/ceramic-new-streams/simulation.yaml
A workflow that can be manually triggered for running keramik performance tests from yaml in this repo under `/performance`.
This workflow is to be called from a future cron based action to schedule periodic runs.
https://docs.github.com/en/actions/using-workflows/reusing-workflows
You can test the `ceramic-new-streams` config now by using this branch in the action.
The `ceramic-anchoring-benchmark` example requires a keramik operator update.
Closes INFRA-99
=> feat: run performance workflow

networks/experimental-rust.yaml
This change adds a network config that runs ceramic one with some experimental flags.
The first flag to test is the event validation
=> feat: run hermetic experimental tests

networks/basic-rust.yaml, networks/experimental-rust.yaml
We default to localhost in the code but keramik needs to address by container name, so the default is changed here. We use the env var for now as the CLI flag isn't merged yet so this var is ignored until that is merged.
=> chore: set eth rpc url for keramik

suite/src/__tests__/correctness/slow/ceramic-cas-integration.test.ts
Tests have been flaky. Anchor would complete but not be detected because the test would timeout. Tests time out after 15 minutes but anchors were projected to take up to 30 minutes. So I increased test timeouts to 30 minutes.
=> chore: increase timeout of slow ceramic-cas integration tests
